language: go
go:
  - 1.7
  - tip

before_script:
  - go get -v github.com/akavel/rsrc

script:
  - go vet $(go list ./... | grep -v /vendor/)
  - go test $(go list ./... | grep -Ev 'vendor|ransomware/cmd')
  - make
